name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMG_NAME: nginx-lite
  IMG_TAG: $(date +%s)
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{env.IMG_NAME}}:${{env.IMG_TAG}}
        docker tag ${{env.IMG_NAME}}:${{env.IMG_TAG}} ${{env.IMG_NAME}}:latest
    - name: List docker images
      run: docker images
